sol(Final):- Final=[[_,_,_,_],[_,_,_,_],[_,_,_,_],[_,_,_,_],[_,_,_,_]],
                    member([kendrick,_,_,_],Final),
                    member([_,jennastar,_,_],Final),
                    member([_,_,walmart,_],Final),
                    member([_,_,walgreens,_],Final),
                    member([_,_,conkeys,_],Final),
                    member([_,_,_,topaz],Final),
                    member([_,_,_,sapphire],Final),
                    member([Ma,jenny,Sc,Gc],Final),Ma\==dane,Ma\==duncan,Gc\==topaz,Sc\==walgreens,
                    member([dane,Wa,Sa,_],Final),Wa\==jennifer,Sa\==walgreens,
                    member([dan,_,Sd,Ga],Final),Ga\==ruby,Sd\==target,Sd\==walmart,
                    member([jay,jen,_,Gb],Final),Gb\==topaz,
                    member([_,jenna,_,opal],Final),
                    member([duncan,_,Sb,emerald],Final),Sb\==target,
                    member([_,_,menards,ruby],Final),
                    member([_,jennifer,target,_],Final).
